# Generated by Django 5.2.5 on 2025-09-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT11', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht11data',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dht11data',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
