# Generated by Django 5.2.5 on 2025-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT11', '0002_dht11data_sensor_id_dht11data_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
