# Generated by Django 5.2.5 on 2025-09-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT11', '0003_alter_dht11data_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11data',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='dht11data',
            name='topic',
        ),
    ]
