# Generated by Django 5.2.6 on 2025-10-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorumidadeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umidadesolo', models.FloatField()),
                ('timestampSolo', models.FloatField()),
            ],
        ),
    ]
